[tool.poetry]
name = "knowledgeable-cobra"
version = "0.1.0"
description = ""
authors = ["Zeyang Lin <4020306+linzeyang@users.noreply.github.com>"]
readme = "README.md"
license = "LICENSE.md"
packages = [
    { include = "app" },
]

[tool.poetry.dependencies]
python = ">=3.10,<3.13"
uvicorn = {extras = ["standard"], version = "^0.23.2"}
langserve = {extras = ["server"], version = "^0.0.39"}
pydantic = {extras = ["email"], version = "^2.5.3"}
python-dotenv = "^1.0.0"
redis = {extras = ["hiredis"], version = "^5.0.1"}
motor = {extras = ["srv"], version = "^3.3.2"}
pymilvus = "^2.3.5"
qdrant-client = "^1.7.1"
weaviate-client = "^3.26.1"
dashscope = "^1.14.0"
dashvector = "^1.0.9"
cohere = "^4.44"
beautifulsoup4 = "^4.12.3"
pypdf = "^4.0.0"
python-multipart = "^0.0.6"
jinja2 = "^3.1.3"
jinja2-fragments = "^1.2.1"
pydantic-settings = "^2.1.0"


[tool.poetry.group.dev.dependencies]
langchain-cli = "^0.0.20"
pytailwindcss = "^0.2.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 88
target-version = ['py310']

[tool.coverage.run]
branch = true
source = [ "./" ]

[tool.coverage.report]
omit = [ "test_*.py", "conftest.py" ]

[tool.isort]
py_version = 310
profile = "black"

[tool.pylint.format]
max-line-length = "88"

[tool.pytest.ini_options]
minversion = "7.0"
testpaths = [ "./" ]
python_files = [ "test_*.py" ]
console_output_style = "count"

[tool.ruff]
line-length = 88
target-version = "py310"
select = ["B", "C", "E", "F", "I", "Q", "S", "W"]
ignore = ["B008", "S104"]
show-source = true
